// Every commit with its time and whether it came before or during the event window (README disclosure; generated, never hand-written).
export type Commit = { hash: string; unix: number; subject: string };
export const WINDOW_START = 1790589600; // 2026-09-28 19:00 KST

const kst = (unix: number) => new Date((unix + 9 * 3600) * 1000).toISOString().replace('T', ' ').slice(0, 16) + ' KST';
export function formatCommits(cs: Commit[]): string {
  const before = cs.filter((c) => c.unix < WINDOW_START).length;
  return [
    '# Every commit — before / during the event window',
    '',
    `Generated by \`npm run commits\` from \`git log\`. Window start: 2026-09-28 19:00 KST. ${cs.length} commits · ${before} before the window · ${cs.length - before} during.`,
    '',
    '| Commit | Time | Window | Subject |',
    '|---|---|---|---|',
    ...cs.map((c) => `| \`${c.hash}\` | ${kst(c.unix)} | ${c.unix < WINDOW_START ? 'before' : 'during'} | ${c.subject.replace(/\|/g, '\\|')} |`),
    '',
  ].join('\n');
}
